[devices]
SW2 ansible_host=192.168.10.234
R3 ansible_host=192.168.10.233
R2 ansible_host=192.168.10.232
R1 ansible_host=192.168.10.231
[devices:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.ios.ios
ansible_user=username
ansible_password=password
ansible_become=yes
